# Generated by Django 5.0.2 on 2024-02-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_connect_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='charity_id',
            new_name='charity',
        ),
        migrations.RenameField(
            model_name='carteddonation',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='carteddonation',
            old_name='donation_id',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_id',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='donationcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='donationcategory',
            old_name='donation_id',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='charity_id',
            new_name='charity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='donation_id',
            new_name='donation',
        ),
    ]
